// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (C) 2026 Nam Jung Hyun (rkttu)
//
// This file is part of MacSandbox, which is dual-licensed:
//   (1) under the GNU Affero General Public License v3.0 or later (see LICENSE), or
//   (2) under a commercial license (see COMMERCIAL-LICENSE.md).
// You may use this file under the terms of either license.
//
// MacSandbox is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.

import Foundation

/// Product brand (fixed name, not localized)
enum Brand {
    static let appName = "macSandbox for Windows"
}

/// External links (help, etc.). Hosted on a GitHub Pages site.
enum HelpLinks {
    static let help = "https://yourtablecloth.github.io/macSandbox/help/"
}

/// App display language option — 'Auto (system setting)' is the default; when explicitly selected, it locks to that language.
enum AppLanguage: String, CaseIterable, Identifiable {
    case auto, en, ko, ja, de, es, fr
    var id: String { rawValue }

    /// Display name in the options UI. Language native names are conventionally not translated.
    var label: String {
        switch self {
        case .auto: return L("options.lang.auto")
        case .en: return "English"
        case .ko: return "한국어"
        case .ja: return "日本語"
        case .de: return "Deutsch"
        case .es: return "Español"
        case .fr: return "Français"
        }
    }
}

/// Localization resolver.
///
/// For two reasons, it locates the resource bundle directly instead of using `Bundle.module`:
/// 1. `Bundle.module.localizedString`'s language selection is constrained to the localizations declared by the
///    main bundle, so even when the system is Korean it falls back to the development language (en) → load the
///    `.lproj` directly to work around this.
/// 2. The `Bundle.module` accessor generated by SwiftPM looks for the resource bundle at `Bundle.main.bundleURL`
///    (= .app root) or the **absolute .build path at build time**, and `fatalError`s if it can't find it.
///    A manually packaged .app places the bundle under `Contents/Resources/`, so the accessor can't find it, and the
///    fallback .build path only exists on the dev machine that built it → **running the distributed build on another
///    machine crashes immediately**. So it searches `Contents/Resources` and the executable directory directly, and
///    even on failure falls back to `Bundle.main` (no crash).
/// Language option changes take effect after an app restart (resolved once at startup).
private final class L10nStore {
    static let shared = L10nStore()
    let bundle: Bundle
    let code: String   // Resolved language code (en/ko/...) — used for resource loading and audit records

    private init() {
        let base = Self.resourceBundle()
        let resolved = Self.resolvedCode()
        self.code = resolved
        if resolved != "en",
           let path = base.path(forResource: resolved, ofType: "lproj"),
           let lproj = Bundle(path: path) {
            bundle = lproj
        } else {
            bundle = base   // Fallback to en (default) or when bundle search fails
        }
    }

    /// Searches the bundle subfolder (`subdir`) for `<lang>.md` in `codes` order and reads it (nil if none).
    /// Per-language markdown such as the terms is placed in a dedicated folder (e.g. `Terms/`) separate from
    /// `.lproj` (UI strings) and bundled via Package.swift's `.copy`.
    static func markdown(inSubdirectory subdir: String, codes: [String]) -> String? {
        let root = resourceBundle()
        for code in codes {
            if let url = root.url(forResource: code, withExtension: "md", subdirectory: subdir),
               let text = try? String(contentsOf: url, encoding: .utf8) {
                return text
            }
        }
        return nil
    }

    /// Locates the SwiftPM resource bundle (`MacSandbox_MacSandbox.bundle`) directly.
    /// Searches .app (Contents/Resources), CLI/swift run (executable directory), and the bundle root in order,
    /// and if not found anywhere, falls back to the main bundle (never fatalErrors).
    private static func resourceBundle() -> Bundle {
        let name = "MacSandbox_MacSandbox.bundle"
        let candidates: [URL?] = [
            Bundle.main.resourceURL,                                  // .app/Contents/Resources
            Bundle.main.bundleURL,                                    // .app root / CLI directory
            Bundle.main.executableURL?.deletingLastPathComponent(),  // swift run executable directory
        ]
        for case let dir? in candidates {
            if let b = Bundle(url: dir.appendingPathComponent(name)) { return b }
        }
        return .main
    }

    private static func resolvedCode() -> String {
        let available = Set(AppLanguage.allCases.map(\.rawValue)).subtracting(["auto"])
        // 1) Language explicitly specified in the options
        if let pref = UserDefaults.standard.string(forKey: AppOptions.kLanguage),
           pref != AppLanguage.auto.rawValue, available.contains(pref) {
            return pref
        }
        // 2) Auto — match against the OS language settings in order ("ko-KR" → "ko")
        for lang in Locale.preferredLanguages {
            let code = String(lang.prefix(2)).lowercased()
            if available.contains(code) { return code }
        }
        return "en"
    }
}

/// UI localization helper.
/// English (en) by default + ko/ja/de/es/fr — when no option is specified, follows the OS language settings.
func L(_ key: String) -> String {
    L10nStore.shared.bundle.localizedString(forKey: key, value: nil, table: nil)
}

/// Format-argument version (`%@`, `%d` — use `%1$@` notation when the order changes in a translation)
func L(_ key: String, _ args: CVarArg...) -> String {
    String(format: L(key), locale: Locale.current, arguments: args)
}

/// The currently resolved language code (for audit records, etc.).
func currentLanguageCode() -> String { L10nStore.shared.code }

/// Reads the per-language markdown (`<lang>.md`) in the bundle subfolder (`subdir`) for the current language (en if absent, nil if still absent).
func bundledMarkdown(inSubdirectory subdir: String) -> String? {
    L10nStore.markdown(inSubdirectory: subdir, codes: [currentLanguageCode(), "en"])
}

/// Reads the markdown for the specified language (`code`) (falls back to en if absent). Used for language switching in the terms viewer.
func bundledMarkdown(inSubdirectory subdir: String, language code: String) -> String? {
    L10nStore.markdown(inSubdirectory: subdir, codes: [code, "en"])
}
